//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dz13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string idClient { get; set; }
        public string clientName { get; set; }
        public bool isPerson { get; set; }
        public string adress { get; set; }
        public double account { get; set; }
        public double invoice { get; set; }
    }
}
