//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dz13
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposits
    {
        public string idClient { get; set; }
        public double amount { get; set; }
        public double percent { get; set; }
        public bool isCapitalised { get; set; }
        public bool isOpened { get; set; }
    }
}
